[platformio]
default_envs = esp32-wifi

[env]
monitor_speed = 115200
upload_speed = 460800
board_build.f_flash = 40000000L

[env:esp32-serial]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<src/serial_main.cpp>

[env:esp32-wifi]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
